### PR TITLE
only-in-session

### PR DESCRIPTION
**Pull request by kaputi**
I added a config to only auto save if already on a session (after saving or loading).

### CODE REVIEW

**Comment by kaputi** [comment]
is to be used with autosave, without it after opening many files in diferent projects when i open the telecope picker i have a lot of sessions, many with similar names, with this functionality i explicitly choose which sessions to save, and the auto save works only on them.

**Comment by Shatur** [comment]
I don't think that such functionality is a good fit for my plugin. I would suggest you to disable autosave and call `:SaveSession` on condition you want in `VimLeavePre` .

**Comment by ranebrown** [comment]
I think I'm running into an issue that would be solved by this.

1. Create a session in a directory with a series of files for a project
2. Close nvim
3.  Run `git commit` and the session gets overwritten by the commit message window.

If autosave only occurred after loading a session this wouldn't happen (if I understand the PR correctly).

**Comment by Shatur** [comment]
> Run git commit and the session gets overwritten by the commit message window.

Are you sure that you using the latest version? It should be fixed by 3fde687a82e0553225cafd9d03b60312688d05c9.

**Comment by ranebrown** [comment]
Just tested on 7f4acf420750d628e4ef6f8784beed7a7ac93524 and got the same behavior.

A git commit buffer isn't the only use case though. If you have a session with any number of open files and you close that for any reason and open another file you lose the session. Seems to me like autosave shouldn't be on if autoload is disabled.

**Comment by Shatur** [comment]
> Seems to me like autosave shouldn't be on if autoload is disabled.

No, I like to save my session even after autoload. But you can set `autosave_last_session` to `false` yourself.

**Comment by ranebrown** [comment]
> No, I like to save my session even after autoload. But you can set autosave_last_session to false yourself.

Totally makes sense. People have different preferences which is why it would be nice to have it as an option.

**Comment by ranebrown** [comment]
FYI: I merged in the changes from this PR and it works great for my use case including fixing the problem with the commit window. Hope you consider merging. Thanks for the plugin!

**Comment by Shatur** [comment]
Okay, if more then one people need it - let's merge. @kaputi, could you rebase to the latest master?

**Comment by Shatur** [comment]
Superseded by #18.

**Pull request closed without merging**
