### PR TITLE
 fix:  Synchronous session load on startup  (#28) 

### PR DESCRIPTION
**Pull request by k1rowashere**
Adds option to load session synchronously on startup to prevent flickering of the intro-screen.
(with readme changes to show how to make it fast)

Implements the solution shown in https://github.com/Shatur/neovim-session-manager/issues/28#issuecomment-2084094392.

demo: (first run without option, second with)
[Screencast from 2024-04-30 18-56-56.webm](https://github.com/Shatur/neovim-session-manager/assets/29287159/e7496e99-abb9-44e7-bfb9-8b66614edce2)

### CODE REVIEW

**Comment by Shatur** [comment]
Thank you!
I tried it and it works just fine without any additional tweaking.
I think that we should make it a non-configurable default behavior.

**Comment by k1rowashere** [comment]
I think this should be labeled as a fix.

**Comment by Shatur** [comment]
Ah, sorry, I wanted to say that we don't need to `vim.schedule` at all :smile: 
I originally wrote this plugin long time ago and didn't have this knowledge back then, but there is a [nice video](https://www.youtube.com/watch?v=GMS0JvS7W1Y) from one of the Neovim main developers.
After looking at this code now, I think that we should just drop `vim.schedule` at all.

**Comment by k1rowashere** [comment]
I assumed there was a reason for the `vim.schedule` so I initially kept it lol.
I reverted everything and just removed `vim.schedule` from `utils.load_session`

**Pull request merged**
