### PR TITLE
fix(utils): error loading session if swap file warning printed

### LINKED ISSUE #72: Opening session with swap file results in error
**Bug description**

Opening a session with a swap file that already exists results in an error after selecting any of the choices brought up by the swap file prompt. This usually happens when one of the files in the session is already open in another editor.

**Steps to reproduce**

<details>
<summary>Minimal configuration</summary>
<br>

```lua
require("session_manager").setup({})
```
</details>

**Expected behavior**
 Session opens normally without throwing error upon selecting one of the options brought up by the swap file prompt.

**Screenshots**

image
image
**Environment**
- OS:  MacOS Ventura
- Desktop environment:  i9-9980HK, AMD Radeon Pro 5550M
- Plugins commit hash:  e7a2cbf56b5fd3a223f2774b535499fc62eca6ef

**Additional context**

```
Error executing vim.schedule lua callback: ...azy/neovim-session-manager/lua/session_manager/utils.lua:82: /Users/joshua/.local/share/nvim/sessions/__U
sers__joshua__.config__nvim, line 19: Vim(edit):E325: ATTENTION
stack traceback:
        [C]: in function 'nvim_command'
        ...azy/neovim-session-manager/lua/session_manager/utils.lua:82: in function <...azy/neovim-session-manager/lua/session_manager/utils.lua:70>
```

### PR DESCRIPTION
**Pull request by Subjective**
Resolves #72

### CODE REVIEW

**Review by Zeioth — APPROVED** [review]

**Comment by Zeioth** [comment]
Sorry for approving way too fast. I've tested the PR and it seems to totally silence/ignore anything related with swapfiles when loading sessions now.

**Comment by Shatur** [comment]
Then #89 should be a better solution?
I aksing because I'm not using swap files.

**Comment by Subjective** [comment]
I still get the swapfile messages when using this config:
```lua
-- NVIM v0.10.0-dev-585+g2e055e49a
{
  "Subjective/neovim-session-manager",
  event = "BufWritePost",
  cmd = "SessionManager",
}
```


Screen Recording 2023-06-27 at 6 48 27 PM

**Comment by Shatur** [comment]
Interesting. Maybe it behaves differently depending on the OS / Neovim version?
@Zeioth what is your configuration?

**Comment by Subjective** [comment]
For reference, I was using this [config](https://github.com/Subjective/minimal-neovim/) on `NVIM v0.10.0-dev-585+g2e055e49a` in the gif.

**Comment by Zeioth** [comment]
@Shatur @Subjective sorry for beign retarded: After updating packages all seem to work as expected. The swap feature works correctly:

Loading a file that has a swap file
screenshot_2023-06-28_17-46-42_778176224

Loading a file that was not saved
screenshot_2023-06-28_17-47-28_234781852

No errors or complaints, all good. Thank you so much both of you for looking into it!!

**Pull request merged**
