### PR TITLE
Fix bug when multiple buffers open in seprate windows.

### PR DESCRIPTION
**Pull request by ysl2**

### CODE REVIEW

**Comment by Shatur** [comment]
Could you describe the bug more?

**Comment by ysl2** [comment]
I have a behavior: when entering vim, do `:bw` first. and the behevior will be recorded into session manager. After re-entering a session, vim reports a notification beacuse there are no buffer to wipe. so change `silent` to `silent!` is only mute the annoying notification and there are no side effect. the pull request is safe.

**Comment by Shatur** [comment]
> I have a behavior: when entering vim, do :bw first. and the behevior will be recorded into session manager. 

Can't reproduce. After `:bw` and re-opening neovim everything is fine.

**Comment by ysl2** [comment]
This notification might occurs when the session has multiple splits.

You can check my init.lua for more info.

https://github.com/ysl2/nvim/blob/f435110c2c49f9110609160bf3c48d8396f62384/lua/ysl/init.lua#LL739C13-L739C13

**Comment by Shatur** [comment]
> This notification might occurs when the session has multiple splits.

Still can't reproduce. Could you provide a minimal reproducible example? Because I think it may be caused by other plugins. Create `minimal.lua` with something like this:
```
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'Shatur/neovim-session-manager',
        requires = {
          'nvim-lua/plenary.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('session_manager').setup()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```
And run with `nvim -nu minimal.lua`.

**Comment by ysl2** [comment]
You are stupid bro. I just add a `!` and no ANY side effect but you let me put a lot of shit code to explain why ? FUCK YOU

**Comment by ysl2** [comment]
I said it's SAFE and no ANY side effect, the bug is actually occured on my host, and I can sure it also can happen on others' host but you think a `!` can mess up your project ? You are entire a piece of shit.

**Comment by ysl2** [comment]
I admire your project, but not you.

**Comment by ysl2** [comment]
FUCK YOU SON OF A BITCH

**Comment by ysl2** [comment]
All I did is to add `!` and the bug eliminated, so you still think it's other plugin's bug ?

Add `!`, no bug. No `!`, bug occured. If you need a test case, get out to check my init.lua !!! I don't want to waste more time to help you do this stupid test. It your responsbility, not mine.

**Comment by Shatur** [comment]
LOL

> no ANY side effect

Except it have. `silent!` will just silently ignore any occurred errors when sourcing file.

> All I did is to add ! and the bug eliminated, so you still think it's other plugin's bug 

Yes, because you just silenced the error. I prefer to fix errors.

>  I don't want to waste more time to help you do this stupid test.

You spent more time writing insults instead of just writing a good report.

**Pull request closed without merging**
