### PR TITLE
Add gitrebase to ignored filetypes

### PR DESCRIPTION
**Pull request by utkarshgupta137**

### CODE REVIEW

**Comment by Shatur** [comment]
When this file created?

**Comment by Shatur** [comment]
> git rebase -i

It creates `git-rebase-todo`.

**Comment by utkarshgupta137** [comment]
> > git rebase -i
> 
> It creates `git-rebase-todo`.

Yeah, but the filetype is `gitrebase`

**Comment by Shatur** [comment]
Oh, sorry, I thought that interactive rebase have `git-rebase-todo` filetype :)

**Pull request merged**
